name: Build

on: 
  push:
     branches:
      - main 
  pull_request:
    branches:
      - main 
jobs:
  first-job:
    runs-on: windows-latest
    steps:
      - name: Check Node.js version
        run: node --version

      - name: Check npm version
        run: npm --version
