name: Build

on: 
  push:

jobs:
  first-job:
    runs-on: windows-latest
    steps:
      - name: Check Node.js version
        run: node --version

      - name: Check npm version
        run: npm --version
